export enum Paths {
    ABOUT = '/about',
    API = '/api',
    AUTH = '/auth',
    AUTHENTICATE = '/authenticate',
    BILLING = '/billing',
    CHAT = '/chat',
    CLOUDINARY = '/cloudinary',
    DASHBOARD = '/dashboard',
    DESIGN = '/design',
    FORGOT_PASSWORD = '/forgot-password',
    HOME = '/',
    INVITATIONS = '/invitations',
    ORGANIZATIONS = '/organizations',
    PAYMENT_SUCCESS = '/payment/success',
    PORTAL = '/portal',
    POSTHOG = '/posthog',
    PROFILE = '/profile',
    RESET_PASSWORD = '/reset-password',
    SHOP = '/shop',
    SIGN_IN = '/sign-in',
    SIGN_OUT = '/sign-out',
    SUCCESS = '/success',
    WEBHOOKS = '/webhooks',
    VERIFY_EMAIL = '/verify-email',
}
