export enum Paths {
    ADMIN = '/admin',
    API = '/api',
    ABOUT = '/about',
    AUTH = '/auth',
    AUTHENTICATE = '/authenticate',
    BILLING = '/billing',
    DASHBOARD = '/dashboard',
    DESIGN = '/design',
    FORGOT_PASSWORD = '/forgot-password',
    HOME = '/',
    INVITATIONS = '/invitations',
    ORGANIZATIONS = '/organizations',
    PAYMENT_SUCCESS = '/payment/success',
    PROFILE = '/profile',
    POSTHOG = '/posthog',
    RESET_PASSWORD = '/reset-password',
    SIGN_IN = '/sign-in',
    SIGN_OUT = '/sign-out',
    VERIFY_EMAIL = '/verify-email',
}
